
export const CATEGORY_LIST_QUERY = "CATEGORY_LIST_QUERY";
export const CATEGORY_LIST_QUERY_SUCESS = "CATEGORY_LIST_QUERY_SUCESS";
export const CATEGORY_LIST_QUERY_FAIL = "CATEGORY_LIST_QUERY_FAIL";



