
export const PRODUCTS_LIST_QUERY = "PRODUCTS_LIST_QUERY";
export const PRODUCTS_LIST_QUERY_SUCESS = "PRODUCTS_LIST_QUERY_SUCESS";
export const PRODUCT_LIST_QUERY_FAIL = "PRODUCT_LIST_QUERY_FAIL";



export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";




export const CHOOSEN_CATEGORY_PRODUCTS_LIST_QUERY =
  "CHOOSEN_CATEGORY_PRODUCTS_LIST_QUERY";
export const CHOOSEN_CATEGORY_PRODUCTS_LIST_QUERY_SUCESS =
  "CHOOSEN_CATEGORY_PRODUCTS_LIST_QUERY_SUCESS";
export const CHOOSEN_CATEGORY_PRODUCT_LIST_QUERY_FAIL =
  "CHOOSEN_CATEGORY_PRODUCT_LIST_QUERY_FAIL";




export const PRODUCTS_TOP_RATED_QUERY = "PRODUCTS_TOP_RATED_QUERY";
export const PRODUCTS_TOP_RATED_QUERY_SUCESS =
  "PRODUCTS_TOP_RATED_QUERY_SUCESS";
export const PRODUCT_TOP_RATED_QUERY_FAIL = "PRODUCT_TOP_RATED_QUERY_FAIL";
